// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"gin-api/rest/app/controller"
	"gin-api/rest/app/service"
)

// Injectors from auth.go:

func Init() controller.AuthController {
	authService := service.NewAuthService()
	authController := controller.NewAuthController(authService)
	return authController
}
