// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package announcement

import (
	"gin-api/rest/app/controller"
	"gin-api/rest/app/repository"
	"gin-api/rest/app/service"
	"gorm.io/gorm"
)

// Injectors from announcement.go:

func Init(db *gorm.DB) controller.AnnouncementController {
	announcementRepository := repository.NewAnnouncementRepository(db)
	announcementService := service.NewAnnouncementService(announcementRepository)
	announcementController := controller.NewAnnouncementController(announcementService)
	return announcementController
}
